### ISSUE TITLE
BTLH distribution map 

### ISSUE THREAD

**Issue by GabySamaniego** [Big-Biodiversity-Collaborative/HummingBird#3]
Hi @klprudic, @ezylstra,  and @jcoliver! 

I'm working on creating a map with the Broad-tailed distribution containing HMN's monitoring sites. 

In the script BTLH_data_exploration, I could read the polygon and make the first map I wanted (map1). 

I want to create a second map based on map1 that contains HMN's monitoring locations, but I had some trouble. I added the points, but the distribution colors (breeding and resident) have changed, and there are many colors in the legend. Also, I couldn't add the labels for each location to the map; I tried geom_label and geom_text, but I couldn't make them work. 

Any help is appreciated, but we can also go through the code tomorrow. I wanted to try writing an issue and see how it works. 
Thanks!

**Comment by ezylstra** [comment]
Added code to overlay banding station locations on range map and retain the appropriate aesthetics in 74ceb1d
